### ISSUE TITLE
Setup Beta Discord forum

### ISSUE THREAD

**Issue by depatchedmode** [everywhere-computer/control-panel#22]
Description: We will setup a private Discord forum within the Fission Discord server that is only accessible to folks who have created Everywhere Computer Fission Server accounts and been accepted into the beta program.

## Job Stories

1. When a developer has finished installing and running their Homestar node:
	- As Fission
		- **Monitor Progress:** We want to know they successfully achieved that milestone, so that we can measure dropoff in our onboarding process
		- **Solicit Feedback:** We want to hear from developers about the process (was it smooth? was it rough?), so that we can qualitatively assess where there might be improvements to be made
		- **Account Gated:** We want only folks who have actually setup an EC account to be able to access the forum, so that the conversation remains focused and there is lower risk of spam.
2. When a developer encounters a problem getting something to work
	+ As the developer
		+ **Get Unblocked:** I want to get help as fast as possible, so that I can continue making progress.
		+ **Async Notifications:** I want to get notified when somebody replies to my request, so that I feel comfortable stepping away to focus on other things.
	+ As Fission
		+ **Maintain Interest:** We want the developer to be helped as fast as possible, so that they don't get discouraged or lose interest in the platform.
		+ **Foster A Supportive Community:** We want developers to be able to help each other as much as possible, so that they strengthen their own knowledge and we have more time to focus on improving the platform.
		+ **Leverage Existing Answers:** We want a knowledge base to accrue over time, so that developers are able to find their way to answers without needing any humans in the loop.

## Measurement

We want to make sure we can track their arrival in the Discord for two reasons:
1. Inclusion in our Plausible onboarding funnel
2. Determining whether to show/hide the "Join Our Discord" prompt w/in Control Panel

## Additional Details

Boris has mentioned that maybe we could leverage Lit protocol for this.

## To do

- [x] Setup the forum
- [x] Populate the form with some default channels
- ~~Implement the account-gated access~~ We'll manually onboard folks for now
- [ ] Link to the forum from the control panel
- [ ] Link to the forum from the docs 
- [ ] Link to the forum from the www

**Comment by depatchedmode** [comment]
Fastest past to this is probably to just do it manually:
+ collect via the intake form
+ they join the Fission Discord server
+ we add them into the beta forum by hand

**Comment by bmann** [comment]
We have a manual process and can re-visit automating / integrating in the future.
